import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  sidemenu,
}: Readonly<{
  children: React.ReactNode
  sidemenu: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <aside className="w-64 h-screen p-4">{sidemenu}</aside>
          <main className="flex-1 p-4">{children}</main>
        </div>
      </body>
    </html>
  )
}
